name: CI
on: [push]

jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: scripts/data-integration-test.json
      ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v1
      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v5
      - name: cache SBT
        uses: coursier/cache-action@v3

      - name: prepare credentials
        run: >
          openssl aes-256-cbc -d \
            -in "$GOOGLE_APPLICATION_CREDENTIALS.enc" \
            -out $GOOGLE_APPLICATION_CREDENTIALS \
            -k $ENCRYPTION_KEY

      - name: Build documentation
        run: sbt $SBT_OPTS scio-examples/compile site/makeSite
        env:
          SOCCO: true
          SBT_OPTS: -Dbigquery.project=data-integration-test -Dbigquery.secret=${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
