jobs:
  make-site:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2.1.0"
      - run: |
          shasum build.sbt \
            project/plugins.sbt \
            project/build.properties > gha.cache.tmp
      - name: "~/.sbt\n\"~/.cache/coursier\"\n cache"
        uses: "actions/cache@v2"
        with:
          key: "${{ runner.os }}-sbt-${{ hashFiles('gha.cache.tmp') }}"
          path: |
            ~/.sbt
            "~/.cache/coursier"
          restore-keys: sbt
      - name: "java 11 setup"
        uses: "olafurpg/setup-java@v6"
        with:
          java-version: "11"
      - run: |
          sbt \
            -Dbigquery.project=dummy \
            scio-examples/compile \
            site/makeSite
        env:
          SOCCO: true
name: site
on:
  pull_request:
    paths:
      - "site/**"
  push:
    paths:
      - "site/**"
